<a href="https://colab.research.google.com/github/nastaranmarzban/pytorch_geometric/blob/master/preprocessing_data_4classdes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount to gdrive to read data, adjacency matrix, p_link and labels. 

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


# Install pandas to read csv files from gdrive. Install torch and numpy which are packages that are needed durind coding.

In [2]:
!pip install pandas
import pandas as pd
import torch
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## It is time to prepare x, edge_index, y, train_mask and test_mask which are needed for PyG. 

**Step1 (preparing x)**: Read multivariate dataset from gdrive and convert the type to what is needed in PyG.

In [3]:
x = pd.read_csv('/gdrive/MyDrive/4classes.sim/df1_t.csv', sep = ',',header = None)
x = x.astype(np.float32) #try to cast all DataFrame columns to specified numpy.dtype
x = torch.tensor(x.values) #convert numpy.dtype to a tensor
print(x.sum(dim = 1).unique().size()) #to see if there is a duplicate data in x or not
print(x.dtype)
print(x.type())
print(x.size())
print(x)

torch.Size([40])
torch.float32
torch.FloatTensor
torch.Size([40, 500])
tensor([[-0.4530,  0.5955, -1.1069,  ...,  0.5985,  0.1790,  0.2985],
        [ 0.2027,  0.6537,  0.6290,  ..., -0.1876, -1.2782,  0.5982],
        [-0.2713,  0.4418,  1.5845,  ..., -1.1430, -2.2012,  0.7388],
        ...,
        [ 0.5176, -1.6871, -1.4386,  ..., -0.2084,  1.3068, -0.1615],
        [ 0.0700, -1.4413, -0.2656,  ..., -0.3264,  1.0155,  0.4870],
        [-0.2865,  1.4095,  1.7289,  ..., -0.3547, -1.7226,  0.7805]])


**Step2 (preparing edge_index)**: Read adjacency matrix from gdrive and convert the type to what is needed in PyG. 

In [4]:
from scipy.sparse import coo_matrix
edge_index_csv = pd.read_csv('/gdrive/MyDrive/4classes.sim/adj_diag_4.csv',sep = ',',header = None)
#print(edge_index_csv)
edge_index_numpy_ndarry = edge_index_csv.values #convert xlsx file to numpy.ndarry
edge_index_coo = coo_matrix(edge_index_numpy_ndarry) #convert symmetric matrix to coo_matrix
print(edge_index_coo)

  (0, 17)	1
  (0, 33)	1
  (1, 18)	1
  (1, 26)	1
  (1, 37)	1
  (2, 5)	1
  (2, 10)	1
  (2, 23)	1
  (2, 25)	1
  (4, 14)	1
  (4, 21)	1
  (4, 29)	1
  (4, 30)	1
  (5, 2)	1
  (5, 16)	1
  (6, 8)	1
  (6, 9)	1
  (6, 14)	1
  (6, 29)	1
  (6, 30)	1
  (6, 34)	1
  (7, 36)	1
  (8, 6)	1
  (8, 9)	1
  (8, 14)	1
  :	:
  (30, 8)	1
  (30, 9)	1
  (30, 14)	1
  (30, 24)	1
  (30, 29)	1
  (32, 18)	1
  (32, 38)	1
  (33, 0)	1
  (34, 6)	1
  (34, 8)	1
  (34, 9)	1
  (34, 14)	1
  (34, 21)	1
  (34, 24)	1
  (35, 26)	1
  (36, 7)	1
  (37, 1)	1
  (37, 11)	1
  (37, 14)	1
  (37, 19)	1
  (37, 26)	1
  (38, 26)	1
  (38, 32)	1
  (39, 14)	1
  (39, 17)	1


In [5]:
edge_index_numpy = np.vstack((edge_index_coo.row, edge_index_coo.col)) #convert coo_matrix to numpy.ndarray
edge_index_torch_int32 = torch.from_numpy(edge_index_numpy) #convert numpy.ndarray to torch.int32
edge_index = edge_index_torch_int32.to(torch.int64) #convert torch.int32 to torch.long
print(edge_index)
print(edge_index.dtype)
print(edge_index.type())
print(edge_index.size())

tensor([[ 0,  0,  1,  1,  1,  2,  2,  2,  2,  4,  4,  4,  4,  5,  5,  6,  6,  6,
          6,  6,  6,  7,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10,
         11, 11, 11, 11, 11, 12, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
         14, 16, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 20, 20, 21, 21, 21, 21,
         21, 21, 22, 23, 24, 24, 24, 24, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26,
         27, 28, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 32, 32,
         33, 34, 34, 34, 34, 34, 34, 35, 36, 37, 37, 37, 37, 37, 38, 38, 39, 39],
        [17, 33, 18, 26, 37,  5, 10, 23, 25, 14, 21, 29, 30,  2, 16,  8,  9, 14,
         29, 30, 34, 36,  6,  9, 14, 29, 30, 34,  6,  8, 21, 29, 30, 34,  2, 11,
         10, 18, 26, 27, 37, 25, 20, 22,  4,  6,  8, 19, 21, 24, 29, 30, 34, 37,
         39,  5,  0, 20, 39,  1, 11, 26, 32, 14, 26, 37, 13, 17,  4,  9, 14, 24,
         29, 34, 13,  2, 14, 21, 30, 34,  2, 12,  1, 11, 18, 19, 28, 35, 37, 38,
         11, 26,  4,  6,  8

**Step3 (preparing y)**: Read labels from gdrive and convert the type to what is needed in PyG.

In [6]:
labels_csv = pd.read_csv('/gdrive/MyDrive/4classes.sim/labels.csv',sep = ',',header = None)
y = torch.tensor(labels_csv.values)
y.resize_((40))
print(y)

tensor([0, 2, 3, 0, 1, 3, 1, 3, 1, 1, 3, 2, 3, 0, 1, 3, 3, 0, 2, 2, 0, 1, 0, 3,
        1, 3, 2, 2, 2, 1, 1, 0, 0, 0, 1, 2, 3, 2, 2, 0])


**Step4 (preparing train_mask, test_mask)**: split x and y into train and test set.

In [7]:
from sklearn.model_selection import train_test_split
main_mask, test_mask, y_main, y_test = train_test_split(x, y,  test_size = 22, random_state = 0, shuffle = True, stratify = y)
train_mask, val_mask, y_train, y_val = train_test_split(main_mask, y_main,  test_size = 10, random_state = 0, shuffle = True, stratify = y_main)
print(train_mask.size())
print(val_mask.size())
print(test_mask.size())
print(train_mask.type())
print(y_train.type())

torch.Size([8, 500])
torch.Size([10, 500])
torch.Size([22, 500])
torch.FloatTensor
torch.LongTensor


## To see how many percent of data belong to each class.

In [8]:
labels, counts = np.unique(y, return_counts = True)
print(counts/float(len(y)))

[0.25 0.25 0.25 0.25]


In [9]:
labels, counts = np.unique(y_train, return_counts = True)
print(counts/float(len(y_train)))

[0.25 0.25 0.25 0.25]


In [10]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_val)))

[0.6 0.6 0.5 0.5]


In [11]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_test)))

[0.27272727 0.27272727 0.22727273 0.22727273]


## Preparing train_mask and test_mask based on PyG.

In [12]:
train_mask = (x.unsqueeze(0) == train_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(train_mask)
print(train_mask.size())
print(sum(train_mask))

val_mask = (x.unsqueeze(0) == val_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(val_mask)
print(val_mask.size())
print(sum(val_mask))

test_mask = (x.unsqueeze(0) == test_mask.unsqueeze(1)).all(dim = 2 ).any(dim = 0)
print(test_mask)
print(test_mask.size())
print(sum(test_mask))

tensor([ True, False, False, False, False,  True, False, False, False,  True,
        False, False,  True, False,  True, False, False, False,  True, False,
        False, False,  True, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False, False])
torch.Size([40])
tensor(8)
tensor([False, False, False, False, False, False, False,  True,  True, False,
        False,  True, False, False, False,  True, False, False, False, False,
         True,  True, False,  True, False, False, False, False,  True, False,
        False,  True, False, False, False, False, False, False,  True, False])
torch.Size([40])
tensor(10)
tensor([False,  True,  True,  True,  True, False,  True, False, False, False,
         True, False, False,  True, False, False,  True,  True, False,  True,
        False, False, False, False,  True,  True,  True, False, False,  True,
         True, False,  True,  True,  True,  True,  True,  True, False,  True])
torch.

## It is time to use p_link as attentions.

In [13]:
p_link = pd.read_csv('/gdrive/MyDrive/4classes.sim/p_links.csv', sep =',',header = None)
p_link = p_link.astype(np.float32)
p_link = torch.tensor(p_link.values)
#p_link = p_link.to(torch.float32)
print(p_link.size())
print(p_link.dtype)
print(p_link.type())

torch.Size([40, 40])
torch.float32
torch.FloatTensor


# Now everything is ready to develop our GNNs.

# Install torch_geometric.

In [14]:
import os
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

1.13.0+cu116
     |████████████████████████████████| 9.4 MB 5.3 MB/s 
     |████████████████████████████████| 4.6 MB 5.3 MB/s 
     |████████████████████████████████| 280 kB 5.1 MB/s 


# Save data in order to use it. 

In [15]:
from torch_geometric.data import Data
Data = Data(x = x, edge_index = edge_index, y = y, train_mask = train_mask, val_mask = val_mask, test_mask = test_mask)
print(Data)

Data(x=[40, 500], edge_index=[2, 126], y=[40], train_mask=[40], val_mask=[40], test_mask=[40])


In [16]:
data_save_name = 'data.pt'  
path = F"/gdrive/MyDrive/4classes.sim/{data_save_name}" 
torch.save(Data.to_dict(), path)

In [17]:
p_link_save_name = 'p_link.pt'  
path = F"/gdrive/MyDrive/4classes.sim/{p_link_save_name}" 
torch.save(p_link, path)